branch-defaults:
  main:
    environment: null
    group_suffix: null
environment-defaults:
  netcontrol-prod:
    branch: null
    repository: null
global:
  application_name: netcontrol-web
  branch: main
  default_ec2_keyname: aws-thejohnweb-eb
  default_platform: node.js-20
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: thejohnweb
  repository: netcontrol-web
  sc: git
  workspace_type: Application
